name             'df_nginx'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures df_nginx'
long_description 'Installs/Configures df_nginx'
version          '0.1.0'
